# Пользователи
## Создать нового пользователя

POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Jack Torrance",
  "email": "torans@overlook.net",
  "avatarPath": "https://15.design.htmlacademy.pro/static/avatar/7.jpg",
  "type": "Pro",
  "password": "shining"
}

###


## Авторизовать пользователя

POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "password": "shining"
}

###

## Отправить изображение

POST http://localhost:4000/users/664cd997a13e0b2257af655c/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< /Users/dyurkin/Downloads/240505_141.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Проверить токен пользователя
GET http://localhost:4000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuc0BvdmVybG9vay5uZXQiLCJmaXJzdG5hbWUiOiJKYWNrIFRvcnJhbmNlIiwiaWQiOiI2NjU1YzhlM2IxYWQwY2M2NDk2NGE2YWIiLCJpYXQiOjE3MTc1ODQ3NTUsImV4cCI6MTcxNzc1NzU1NX0.vxe4BOQ9MOdzT_qSgYGKFGolg5M_rf4rKVa4YRTAdcs

###
