# Пользователи
## Создать нового пользователя

POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Cristiano Ronaldo",
  "email": "criro@portugal.por",
  "type": "Pro",
  "password": "seeeee"
}

###


## Авторизовать пользователя

POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "criro@portugal.por",
  "password": "seeeee"
}

###

## Отправить изображение

POST http://localhost:4000/users/664cd997a13e0b2257af655c/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< /Users/dyurkin/Downloads/240505_141.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

## Проверить токен пользователя
GET http://localhost:4000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImNyaXJvQHBvcnR1Z2FsLnBvciIsImlkIjoiNjY2NzA4YTZiZjRmODdiNzY4NWJkZTcwIiwiaWF0IjoxNzE4MDk1OTMyLCJleHAiOjE3MTgyNjg3MzJ9.sJcH_YtIgazQIM9REVeVmruzqDE_dREteoTFwXE2EFQ

###
