# Предлоджения (Offers)
## Получить список предложений
GET http://localhost:4000/offers HTTP/1.1
Content-Type: application/json

###

# Получить объявление по идентификатору
GET http://localhost:4000/offers/66717df9323269b4b927e965 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImNyaXJvQHBvcnR1Z2FsLnBvciIsImlkIjoiNjY2NzA4YTZiZjRmODdiNzY4NWJkZTcwIiwiaWF0IjoxNzE4Njk1MTE5LCJleHAiOjE3MTg4Njc5MTl9.A2dALujeD5zimxMtQsHpx2qrrvtSGNLuEKhn7HuAsIY

###

## Создать новое предложение
POST http://localhost:4000/offers HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImNyaXJvQHBvcnR1Z2FsLnBvciIsImlkIjoiNjY2NzA4YTZiZjRmODdiNzY4NWJkZTcwIiwiaWF0IjoxNzE4Njk1MTE5LCJleHAiOjE3MTg4Njc5MTl9.A2dALujeD5zimxMtQsHpx2qrrvtSGNLuEKhn7HuAsIY

{
    "title": "Appartment in modern style 3",
    "description": "Elegant apartment with two bedrooms, a fireplace in the living room, and a view of the park. The area has well-developed infrastructure and convenient transportation access.",
    "postDate": "2024-05-15T17:27:07.513Z",
    "city": "Amsterdam",
    "previewImage": "https://15.design.htmlacademy.pro/static/hotel/.jpg",
    "images": [
        "https://15.design.htmlacademy.pro/static/hotel/.jpg",
        "https://15.design.htmlacademy.pro/static/hotel/.jpg",
        "https://15.design.htmlacademy.pro/static/hotel/.jpg",
        "https://15.design.htmlacademy.pro/static/hotel/.jpg"
    ],
    "isPremium": true,
    "rating": 4,
    "type": "room",
    "bedrooms": 4,
    "maxAdults": 5,
    "price": 800,
    "goods": [
        "Laptop friendly workspace",
        "Baby seat",
        "Washer",
        "Towels"
    ],
    "userId": "605c72c6f4b1f8375c8b4567",
    "numberOfComments": 51,
    "location": {
        "latitude": 52.370216,
        "longitude": 4.895168
    }
}

###

## Удалить объявление по идентификатору

DELETE http://localhost:4000/offers/666956c5135d3bb2b9c91f79 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImNyaXJvQHBvcnR1Z2FsLnBvciIsImlkIjoiNjY2NzA4YTZiZjRmODdiNzY4NWJkZTcwIiwiaWF0IjoxNzE4Njk1MTE5LCJleHAiOjE3MTg4Njc5MTl9.A2dALujeD5zimxMtQsHpx2qrrvtSGNLuEKhn7HuAsIY

###

## Обновить объявление

PATCH http://localhost:4000/offers/666956c5135d3bb2b9c91f79 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImNyaXJvQHBvcnR1Z2FsLnBvciIsImlkIjoiNjY2NzA4YTZiZjRmODdiNzY4NWJkZTcwIiwiaWF0IjoxNzE4Njk1MTE5LCJleHAiOjE3MTg4Njc5MTl9.A2dALujeD5zimxMtQsHpx2qrrvtSGNLuEKhn7HuAsIY

{
  "title": "Appartment in modern style 2 CHANGED",
  "description": "Description wioeunvwipeunvwienvwiev CHANGED",
  "price": 1000
}

###

## Изменить состояние флага isFavorite
PUT http://localhost:4000/offers/favorites/664cd997a13e0b2257af655e/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImNyaXJvQHBvcnR1Z2FsLnBvciIsImlkIjoiNjY2NzA4YTZiZjRmODdiNzY4NWJkZTcwIiwiaWF0IjoxNzE4Njk1MTE5LCJleHAiOjE3MTg4Njc5MTl9.A2dALujeD5zimxMtQsHpx2qrrvtSGNLuEKhn7HuAsIY

{
  "isFavorite": true
}

###

## Получить список избранных предложений для пользователя
GET http://localhost:4000/offers/favorites HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImNyaXJvQHBvcnR1Z2FsLnBvciIsImlkIjoiNjY2NzA4YTZiZjRmODdiNzY4NWJkZTcwIiwiaWF0IjoxNzE4Njk1MTE5LCJleHAiOjE3MTg4Njc5MTl9.A2dALujeD5zimxMtQsHpx2qrrvtSGNLuEKhn7HuAsIY

###

## Получить список премиальных предложений по городу
GET http://localhost:4000/offers/premium HTTP/1.1
Content-Type: application/json

  {
    "city": "Paris"
  }

###

## Загрузить изображение для объявления
POST http://localhost:4000/offers/664cd997a13e0b2257af656b/image HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImNyaXJvQHBvcnR1Z2FsLnBvciIsImlkIjoiNjY2NzA4YTZiZjRmODdiNzY4NWJkZTcwIiwiaWF0IjoxNzE4Njk1MTE5LCJleHAiOjE3MTg4Njc5MTl9.A2dALujeD5zimxMtQsHpx2qrrvtSGNLuEKhn7HuAsIY
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="screen.png"
Content-Type: image/png

< /Users/spider_net/Downloads/240601_214.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
