export const EComponent = {
  AuthService: Symbol.for('AuthService'),
  AuthExceptionFilter: Symbol.for('AuthExceptionFilter'),
  CityModel: Symbol.for('CityModel'),
  CityService: Symbol.for('CityService'),
  CommentController: Symbol.for('CommentController'),
  CommentService: Symbol.for('CommentService'),
  CommentModel: Symbol.for('CommentModel'),
  Config: Symbol.for('Config'),
  DatabaseClient: Symbol.for('DatabaseClient'),
  ExceptionFilter: Symbol.for('ExceptionFilter'),
  HttpExceptionFilter: Symbol.for('HttpExceptionFilter'),
  LocationModel: Symbol.for('LocationModel'),
  LocationService: Symbol.for('LocationService'),
  Logger: Symbol.for('Logger'),
  OfferModel: Symbol.for('OfferModel'),
  OfferService: Symbol.for('OfferService'),
  OfferController: Symbol.for('OfferController'),
  RestApplication: Symbol.for('RestApplication'),
  ValidationExceptionFilter: Symbol.for('ValidationExceptionFilter'),
  UserController: Symbol.for('UserController'),
  UserModel: Symbol.for('UserModel'),
  UserService: Symbol.for('UserService')
} as const;
